---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-to-eks-deployment
spec:
  selector:
    matchLabels:
      run: ecr-to-eks-deployment
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        run: ecr-to-eks-deployment
    spec:
      containers:
      - name: ecr-to-eks-deployment
        image: 212294556799.dkr.ecr.us-west-2.amazonaws.com/scalable-personal-profile-page:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80